import 'bootstrap/dist/css/bootstrap.min.css';
import 'globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';

export const metadata = {
  title: 'Next.js 13 - User Registration and Login Example',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body>
      <AntdRegistry>{children}</AntdRegistry>
    </body>
  </html>
);

export default RootLayout;